# Generated by Django 4.0.4 on 2022-04-21 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('equiped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Armor', 'Armor'), ('Books', 'Books'), ('Food', 'Food'), ('Jewelery', 'Jewelery'), ('Materials', 'Materials'), ('Potions', 'Potions'), ('Weapons', 'Weapons')], max_length=50)),
                ('weight', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=500)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Dawnstar', 'Dawnstar'), ('Falkreath', 'Falkreath'), ('Markarth', 'Markarth'), ('Morthal', 'Morthal'), ('Riften', 'Riften'), ('Solitude', 'Solitude'), ('Whiterun', 'Whiterun'), ('Winterhold', 'Winterhold'), ('Windhelm', 'Windhelm')], max_length=50)),
                ('avatar', models.CharField(choices=[('Altmer', 'Altmer'), ('Argonian', 'Argonian'), ('Bosmer', 'Bosmer'), ('Breton', 'Breton'), ('Dunmer', 'Dunmer'), ('Imperial', 'Imperial'), ('Khajiit', 'Khajiit'), ('Nord', 'Nord'), ('Orsimer', 'Orsimer'), ('Redguard', 'Redguard'), ('...', '...')], max_length=50)),
                ('bag', models.ManyToManyField(through='main_app.Cart', to='main_app.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
