# Generated by Django 4.0.3 on 2022-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_checkoutaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Armor', 'Armor'), ('Books', 'Books'), ('Food', 'Food'), ('Jewelery', 'Jewelery'), ('Potions', 'Potions'), ('Weapons', 'Weapons')], max_length=50),
        ),
    ]
